# This workflow runs the native extension tests with sanitizers.

name: Sanitizers
on: [push]
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0'
        bundler-cache: true
    - name: Build with ASan and UBSan
      run: EDHOC_SANITIZERS=address,undefined bundle exec rake compile
    - name: Run sanitizer tests
      run: |
        export LD_PRELOAD="$(gcc -print-file-name=libasan.so)"
        ASAN_OPTIONS=detect_leaks=0:halt_on_error=1 UBSAN_OPTIONS=halt_on_error=1 bundle exec sus
