# This workflow builds the native extension and runs Sus tests.

name: Sus
on: [push]
jobs:
  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.4', '4.0']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: actions/setup-python@v7
      with:
        python-version: '3.x'
    - run: python -m pip install -r vendor/libedhoc/externals/mbedtls/tf-psa-crypto/scripts/driver.requirements.txt
    - run: bundle exec rake compile
    - run: bundle exec sus
